.section .rodata

.section .text
 
.option norvc
 
.type _start, @function
.global _start
_start:
	.cfi_startproc
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	addi x1, x1, 1
	ecall
	.cfi_endproc

.end

